### ISSUE TITLE
RxSwift 5 

### ISSUE THREAD

**Issue by grangej** [RxSwiftCommunity/RxCocoa-Texture#18]
When attempting to make this library compatible with RxSwift 5 I ended up having to rename the bind functions as they seem to conflict with RxRelay. 

On my fork I was able to get this working by renaming all bind functions to asBind(xxxx) 

Not sure if you have any other suggestions? If not I can go ahead and cleanup my code and create a PR for an RxSwift 5.x version off this library.

**Comment by GeekTree0101** [comment]
You can see RxSwift 5.0 integrated RxCocoa-Texture :) Thanks
https://github.com/RxSwiftCommunity/RxCocoa-Texture/tree/3.0.0

**Comment by GeekTree0101** [comment]
Now RxCocoa-Texture supports RxSwift5.0 :)
