### ISSUE TITLE
Some suggestion

### ISSUE THREAD

**Issue by harryzjm** [RxSwiftCommunity/RxCocoa-Texture#26]
could you depend on only Texture/Core, because this lib don`t use PINRemoteImage or other libraries, and also Texture 2.8.1 is released

**Comment by GeekTree0101** [comment]
Thanks for your suggestion. Unfortunately, ASNetworkImageNode reactive extension must be depend on  PINRemoteImage. 
I will consider your suggestion as soon as possible.
