### ISSUE TITLE
Master branch can not use node.safeAreaInsets in Texture 2.7

### ISSUE THREAD

**Issue by Arcovv** [RxSwiftCommunity/RxCocoa-Texture#4]
If can not use `safeAreaInsets`, app also could not adopt iPhone X / XS / XR

**Comment by GeekTree0101** [comment]
master branch doesn;t support texture 2.7
In Texture 2.7 case, please use https://github.com/GeekTree0101/RxCocoa-Texture/tree/Texture-2.7 branch.

Thank you @Arcovv

**Comment by Arcovv** [comment]
Oh I see. But now I need it update to Swift 4.2. I do it in my folk. Would you want me to make a PR?
https://github.com/Arcovv/RxCocoa-Texture/commit/084ee2369b57a44c2d5750bdc56d946eb394f3cf

**Comment by GeekTree0101** [comment]
@Arcovv Great contribution!.
But, I will separate cocoapods base on swift version 4.0 with 4.2. 
At that time, can you make PR on this repository as cross fork?

**Comment by Arcovv** [comment]
If you want to support Swift 4.0, I suggest you to use typealias and macro to adopt.
When you want to do like this, maybe I can help you~
But I do not know what else you want to for different versions.

**Comment by GeekTree0101** [comment]
@Arcovv, If you don't mind, can you make pull request base on Texture-2.7 branch and master branch?

**Comment by GeekTree0101** [comment]
@Arcovv Now Swift4.2 migrated version released! Thank you for supporting.

**Comment by Arcovv** [comment]
Great~
